/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ["./src/**/*.{js,jsx,ts,tsx}"],
    theme: {
        screens: {
            xs: "0px",
            sm: "576px",
            md: "768px",
            lg: "992px",
            xl: "1200px",
            xxl: "1440px",
        },
        spacing: {
            px: "1px",
            0: "0",
            1: "0.25rem",
            2: "0.5rem",
            3: "0.75rem",
            4: "1rem",
            5: "1.25rem",
            6: "1.5rem",
            8: "2rem",
            10: "2.5rem",
            12: "3rem",
            16: "4rem",
            20: "5rem",
            24: "6rem",
            32: "8rem",
            40: "10rem",
            48: "12rem",
            56: "14rem",
            64: "16rem",
        },
        padding: {
            px: "1px",
            0: "0",
            1: "0.25rem",
            2: "0.5rem",
            3: "0.75rem",
            4: "1rem",
            5: "1.25rem",
            6: "1.5rem",
            8: "2rem",
            10: "2.5rem",
            12: "3rem",
            16: "4rem",
            20: "5rem",
            24: "6rem",
            32: "8rem",
            40: "10rem",
            48: "12rem",
            56: "14rem",
            64: "16rem",
        },
        margin: {
            px: "1px",
            0: "0",
            1: "0.25rem",
            2: "0.5rem",
            3: "0.75rem",
            4: "1rem",
            5: "1.25rem",
            6: "1.5rem",
            8: "2rem",
            10: "2.5rem",
            12: "3rem",
            16: "4rem",
            20: "5rem",
            24: "6rem",
            32: "8rem",
            40: "10rem",
            48: "12rem",
            56: "14rem",
            64: "16rem",
        },
        fontFamily: {
            sans: [
                "system-ui",
                "-apple-system",
                "BlinkMacSystemFont",
                '"Segoe UI"',
                "Roboto",
                '"Helvetica Neue"',
                "Arial",
                '"Noto Sans"',
                "sans-serif",
                '"Apple Color Emoji"',
                '"Segoe UI Emoji"',
                '"Segoe UI Symbol"',
                '"Noto Color Emoji"',
            ],
            serif: [
                "Georgia",
                "Cambria",
                '"Times New Roman"',
                "Times",
                "serif",
            ],
            mono: [
                "Menlo",
                "Monaco",
                "Consolas",
                '"Liberation Mono"',
                '"Courier New"',
                "monospace",
            ],
        },
        fontSize: {
            mammoth: "8rem",
            xs: "0.75rem",
            sm: "0.875rem",
            base: "1rem",
            lg: "1.125rem",
            xl: "1.25rem",
            "2xl": "1.5rem",
            "3xl": "1.875rem",
            "4xl": "2.25rem",
            "5xl": "3rem",
            "6xl": "4rem",
        },
        fontWeight: {
            hairline: "100",
            thin: "200",
            light: "300",
            normal: "400",
            medium: "500",
            semibold: "600",
            bold: "700",
            extrabold: "800",
            black: "900",
        },
        colors: {
            bgDefault: "rgba(32, 33, 37, 0.12)",
            brightRed: "hsl(12, 88%, 59%)",
            brightRedLight: "hsl(12, 88%, 69%)",
            brightRedSupLight: "hsl(12, 88%, 95%)",
            darkBlue: "hsl(228, 39%, 23%)",
            darkGrayishBlue: "hsl(227, 12%, 61%)",
            veryDarkBlue: "hsl(233, 12%, 13%)",
            veryPaleRed: "hsl(13, 100%, 96%)",
            veryLightGray: "hsl(0, 0%, 98%)",
        },
        opacity: {
            0: "0",
            25: "0.25",
            50: "0.5",
            75: "0.75",
            100: "1",
        },
        cursor: {
            auto: "auto",
            default: "default",
            pointer: "pointer",
            wait: "wait",
            text: "text",
            move: "move",
            "not-allowed": "not-allowed",
        },
        borderRadius: {
            none: "0",
            sm: "0.125rem",
            default: "0.25rem",
            md: "0.375rem",
            lg: "0.5rem",
            full: "9999px",
        },
        borderWidth: {
            default: "1px",
            0: "0",
            2: "2px",
            4: "4px",
            8: "8px",
        },
        boxShadow: {
            xs: "0 0 0 1px rgba(0, 0, 0, 0.05)",
            sm: "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
            default:
                "0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)",
            md:
                "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
            lg:
                "0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)",
            xl:
                "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)",
            "2xl": "0 25px 50px -12px rgba(0, 0, 0, 0.25)",
            inner: "inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)",
            outline: "0 0 0 3px rgba(66, 153, 225, 0.5)",
            none: "none",
        },
    },
    plugins: [],
};
